### ISSUE TITLE
Error at re-compilation: Cannot read property 'has' of null

### ISSUE THREAD

**Issue by gilhardl** [gilhardl/git-mirroring#1]
Get the following error when the app get recompiled :
```
return _this.modifiedResourceFiles.has(resourcePath);
                                           ^

TypeError: Cannot read property 'has' of null
    at /c/Users/LG/code/LG/git-mirroring/node_modules/@angular/compiler-cli/src/ngtsc/incremental/src/state.js:146:44
    at Array.some (<anonymous>)
    at IncrementalState.hasChangedResourceDependencies (/c/Users/LG/code/LG/git-mirroring/node_modules/@angular/compiler-cli/src/ngtsc/incremental/src/state.js:145:46)
    at IncrementalState.safeToSkip (/c/Users/LG/code/LG/git-mirroring/node_modules/@angular/compiler-cli/src/ngtsc/incremental/src/state.js:92:46)
    at IvyCompilation.analyze (/c/Users/LG/code/LG/git-mirroring/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:156:39)
    at IvyCompilation.analyzeSync (/c/Users/LG/code/LG/git-mirroring/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:71:76)
    at /c/Users/LG/code/LG/git-mirroring/node_modules/@angular/compiler-cli/src/ngtsc/program.js:257:39
    at Array.forEach (<anonymous>)
    at NgtscProgram.ensureAnalyzed (/c/Users/LG/code/LG/git-mirroring/node_modules/@angular/compiler-cli/src/ngtsc/program.js:255:22)
    at NgtscProgram.getNgSemanticDiagnostics (/c/Users/LG/code/LG/git-mirroring/node_modules/@angular/compiler-cli/src/ngtsc/program.js:167:36)
```

**Comment by gilhardl** [comment]
https://github.com/angular/angular/issues/31328
